# Generated by Django 6.0 on 2025-12-14 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_groups'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groups',
            new_name='Group',
        ),
    ]
