# Generated by Django 5.2.6 on 2025-12-14 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_group_alter_group_id_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'Yanvar'), (2, 'Fevral'), (3, 'Mart'), (4, 'Aprel'), (5, 'May'), (6, 'İyun'), (7, 'İyul'), (8, 'Avqust'), (9, 'Sentyabr'), (10, 'Oktyabr'), (11, 'Noyabr'), (12, 'Dekabr')], verbose_name='Ay')),
                ('year', models.IntegerField(default=2025, verbose_name='İl')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Ödəniş edilib')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_payments', to=settings.AUTH_USER_MODEL, verbose_name='Tələbə')),
            ],
            options={
                'verbose_name': 'Aylıq Ödəniş',
                'verbose_name_plural': 'Aylıq Ödənişlər',
                'ordering': ['year', 'month'],
                'unique_together': {('user', 'month', 'year')},
            },
        ),
    ]
