# Generated by Django 5.2.6 on 2025-12-14 11:58

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_monthlypayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlypayment',
            name='year',
            field=models.IntegerField(default=account.models.get_current_year, verbose_name='İl'),
        ),
    ]
